import { SchoolSummary, StudentProfile, ScreeningSession } from './types';
import { DEFAULT_FALLBACK_PX_PER_MM } from './optotypeMath';

export const DEMO_SCHOOLS: SchoolSummary[] = [
  {
    schoolId: 'sch-sankara-01',
    schoolName: 'Sankara Vidyalaya Higher Secondary School, Pammal',
    location: 'Chennai, Tamil Nadu',
    contactPerson: 'Mrs. Lakshmi Narayanan (Principal)',
    phone: '+91 94440 12345',
    totalStudentsRegistered: 480,
    totalScreened: 412,
    normalCount: 342,
    recheckCount: 38,
    referralCount: 32,
    followupsCompleted: 24,
  },
  {
    schoolId: 'sch-sankara-02',
    schoolName: 'Sri Kanchi Sankara Public School, Kanchipuram',
    location: 'Kanchipuram, Tamil Nadu',
    contactPerson: 'Mr. R. Raghavan (Coordinator)',
    phone: '+91 98841 67890',
    totalStudentsRegistered: 350,
    totalScreened: 320,
    normalCount: 275,
    recheckCount: 24,
    referralCount: 21,
    followupsCompleted: 18,
  },
  {
    schoolId: 'sch-sankara-03',
    schoolName: 'Sankara Eye Academy Model School, Coimbatore',
    location: 'Coimbatore, Tamil Nadu',
    contactPerson: 'Dr. Priya Sundaram',
    phone: '+91 97900 34567',
    totalStudentsRegistered: 520,
    totalScreened: 460,
    normalCount: 395,
    recheckCount: 35,
    referralCount: 30,
    followupsCompleted: 26,
  },
  {
    schoolId: 'sch-sankara-04',
    schoolName: 'Government Model High School, Sector 4',
    location: 'Bangalore, Karnataka',
    contactPerson: 'Mr. B. Suresh',
    phone: '+91 98450 99887',
    totalStudentsRegistered: 290,
    totalScreened: 245,
    normalCount: 198,
    recheckCount: 27,
    referralCount: 20,
    followupsCompleted: 14,
  }
];

export const DEMO_STUDENTS: StudentProfile[] = [
  {
    studentId: 'std-a8F7k29LmQ',
    opCardId: 'SEH-OP-2026-8812',
    qrId: 'a8F7k29LmQ',
    name: 'Aarav Sharma',
    schoolId: 'sch-sankara-01',
    schoolName: 'Sankara Vidyalaya Higher Secondary School, Pammal',
    gradeClass: 'Class 4',
    section: 'A',
    age: 9,
    gender: 'M',
    parentContactMasked: '+91 98*** **451',
  },
  {
    studentId: 'std-k3P9x42VwR',
    opCardId: 'SEH-OP-2026-8813',
    qrId: 'k3P9x42VwR',
    name: 'Diya Krishnan',
    schoolId: 'sch-sankara-01',
    schoolName: 'Sankara Vidyalaya Higher Secondary School, Pammal',
    gradeClass: 'Class 3',
    section: 'B',
    age: 8,
    gender: 'F',
    parentContactMasked: '+91 94*** **823',
  },
  {
    studentId: 'std-m5N8y17QzT',
    opCardId: 'SEH-OP-2026-8814',
    qrId: 'm5N8y17QzT',
    name: 'Rohan Patel',
    schoolId: 'sch-sankara-02',
    schoolName: 'Sri Kanchi Sankara Public School, Kanchipuram',
    gradeClass: 'Class 5',
    section: 'A',
    age: 10,
    gender: 'M',
    parentContactMasked: '+91 97*** **199',
  },
  {
    studentId: 'std-p2W6c94LbM',
    opCardId: 'SEH-OP-2026-8815',
    qrId: 'p2W6c94LbM',
    name: 'Ananya Reddy',
    schoolId: 'sch-sankara-03',
    schoolName: 'Sankara Eye Academy Model School, Coimbatore',
    gradeClass: 'Class 4',
    section: 'C',
    age: 9,
    gender: 'F',
    parentContactMasked: '+91 99*** **344',
  },
  {
    studentId: 'std-t7R4b12KnS',
    opCardId: 'SEH-OP-2026-8816',
    qrId: 't7R4b12KnS',
    name: 'Mohammed Faisal',
    schoolId: 'sch-sankara-04',
    schoolName: 'Government Model High School, Sector 4',
    gradeClass: 'Class 6',
    section: 'B',
    age: 11,
    gender: 'M',
    parentContactMasked: '+91 98*** **772',
  }
];

export const DEMO_SCREENING_SESSIONS: ScreeningSession[] = [
  {
    sessionId: 'sess-demo-001',
    studentId: 'std-a8F7k29LmQ',
    opCardId: 'SEH-OP-2026-8812',
    qrId: 'a8F7k29LmQ',
    schoolId: 'sch-sankara-01',
    schoolName: 'Sankara Vidyalaya Higher Secondary School, Pammal',
    gradeClass: 'Class 4',
    section: 'A',
    deviceId: 'iPad-Air-ScreeningUnit-01',
    startedAt: '2026-03-02T09:15:00Z',
    completedAt: '2026-03-02T09:19:30Z',
    testDistanceCm: 150,
    calibration: {
      pxPerMm: DEFAULT_FALLBACK_PX_PER_MM,
      calibratedObjectWidthMm: 85.6,
      userAdjustedPx: 324,
      dpr: 2,
      screenWidth: 820,
      screenHeight: 1180,
      viewportWidth: 820,
      viewportHeight: 1180,
      userAgent: 'Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X)',
      calibratedAt: '2026-03-02T09:14:00Z',
      method: 'card',
    },
    rightEyeResult: {
      eye: 'right',
      smallestIdentifiedMm: 3.27,
      snellenEquivalent: '6/9',
      logMarEquivalent: 0.18,
      trialsPassed: 4,
      totalTrials: 4,
      passedThreshold: true,
      rawResponses: [],
    },
    leftEyeResult: {
      eye: 'left',
      smallestIdentifiedMm: 3.27,
      snellenEquivalent: '6/9',
      logMarEquivalent: 0.18,
      trialsPassed: 4,
      totalTrials: 4,
      passedThreshold: true,
      rawResponses: [],
    },
    colourVisionResult: {
      tested: true,
      platesCount: 5,
      correctCount: 5,
      status: 'normal',
      summaryText: 'Colour vision screening: No concern detected',
      responses: [],
    },
    overallStatus: 'normal',
    referralRequired: false,
    syncStatus: 'synced',
    offlineCreated: false,
    responses: [],
  },
  {
    sessionId: 'sess-demo-002',
    studentId: 'std-k3P9x42VwR',
    opCardId: 'SEH-OP-2026-8813',
    qrId: 'k3P9x42VwR',
    schoolId: 'sch-sankara-01',
    schoolName: 'Sankara Vidyalaya Higher Secondary School, Pammal',
    gradeClass: 'Class 3',
    section: 'B',
    deviceId: 'Android-Tablet-ScreeningUnit-03',
    startedAt: '2026-03-02T10:05:00Z',
    completedAt: '2026-03-02T10:11:00Z',
    testDistanceCm: 150,
    calibration: {
      pxPerMm: DEFAULT_FALLBACK_PX_PER_MM,
      calibratedObjectWidthMm: 85.6,
      userAdjustedPx: 320,
      dpr: 1.5,
      screenWidth: 800,
      screenHeight: 1280,
      viewportWidth: 800,
      viewportHeight: 1280,
      userAgent: 'Mozilla/5.0 (Linux; Android 14)',
      calibratedAt: '2026-03-02T10:04:00Z',
      method: 'card',
    },
    rightEyeResult: {
      eye: 'right',
      smallestIdentifiedMm: 8.73,
      snellenEquivalent: '6/24',
      logMarEquivalent: 0.60,
      trialsPassed: 2,
      totalTrials: 4,
      passedThreshold: false,
      rawResponses: [],
    },
    leftEyeResult: {
      eye: 'left',
      smallestIdentifiedMm: 4.36,
      snellenEquivalent: '6/12',
      logMarEquivalent: 0.30,
      trialsPassed: 3,
      totalTrials: 4,
      passedThreshold: false,
      rawResponses: [],
    },
    colourVisionResult: {
      tested: true,
      platesCount: 5,
      correctCount: 4,
      status: 'normal',
      summaryText: 'Colour vision screening: No concern detected',
      responses: [],
    },
    overallStatus: 'referral',
    referralRequired: true,
    referralStatus: 'parent_informed',
    clinicalNotes: 'Right eye significantly reduced acuity (6/24). Inter-ocular difference >= 2 lines. Suspected uncorrected refractive error / anisometropic amblyopia risk. Parent notification letter generated.',
    syncStatus: 'synced',
    offlineCreated: false,
    responses: [],
  },
  {
    sessionId: 'sess-demo-003',
    studentId: 'std-m5N8y17QzT',
    opCardId: 'SEH-OP-2026-8814',
    qrId: 'm5N8y17QzT',
    schoolId: 'sch-sankara-02',
    schoolName: 'Sri Kanchi Sankara Public School, Kanchipuram',
    gradeClass: 'Class 5',
    section: 'A',
    deviceId: 'Mobile-Chrome-Staff-02',
    startedAt: '2026-03-02T11:20:00Z',
    completedAt: '2026-03-02T11:25:10Z',
    testDistanceCm: 150,
    calibration: {
      pxPerMm: DEFAULT_FALLBACK_PX_PER_MM,
      calibratedObjectWidthMm: 85.6,
      userAdjustedPx: 328,
      dpr: 3,
      screenWidth: 390,
      screenHeight: 844,
      viewportWidth: 390,
      viewportHeight: 844,
      userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_4)',
      calibratedAt: '2026-03-02T11:19:00Z',
      method: 'card',
    },
    rightEyeResult: {
      eye: 'right',
      smallestIdentifiedMm: 4.36,
      snellenEquivalent: '6/12',
      logMarEquivalent: 0.30,
      trialsPassed: 3,
      totalTrials: 4,
      passedThreshold: true,
      rawResponses: [],
    },
    leftEyeResult: {
      eye: 'left',
      smallestIdentifiedMm: 4.36,
      snellenEquivalent: '6/12',
      logMarEquivalent: 0.30,
      trialsPassed: 3,
      totalTrials: 4,
      passedThreshold: true,
      rawResponses: [],
    },
    colourVisionResult: {
      tested: true,
      platesCount: 5,
      correctCount: 2,
      status: 'concern',
      summaryText: 'Colour vision screening: Further assessment recommended',
      responses: [],
    },
    overallStatus: 'recheck',
    referralRequired: false,
    referralStatus: 'recommended',
    clinicalNotes: 'Acuity borderline 6/12 bilateral. Red-green color discrimination flagged. Re-check in good natural daylight recommended before formal ophthalmic referral.',
    syncStatus: 'synced',
    offlineCreated: false,
    responses: [],
  }
];
